name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      run-checks: ${{ !fromJSON(steps.changed-files.outputs.only_modified) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get only modified files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            docs/**
            .github/**
            !.github/workflows/ci.yaml
            **/*.md
  build:
    name: Run Build
    needs: changed-files
    if: fromJSON(needs.changed-files.outputs.run-checks)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

  lint:
    name: Run Lint
    needs: changed-files
    if: fromJSON(needs.changed-files.outputs.run-checks)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

  test:
    name: Run Tests
    needs: changed-files
    if: fromJSON(needs.changed-files.outputs.run-checks)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
